### ISSUE TITLE
Добавление новой задачи

### ISSUE THREAD

**Issue by asmazovec** [vpo-tusur/todo-api#18]
## Цель фичи

Позволяет пользователю создавать задачу за выбранную дату.

## Основной сценарий использования

1. Пользователь отправляет POST запрос на URL `/tasks` с телом запроса, содержащим информацию о новой задаче.
Формат запроса в соответствии с [ТЗ](https://github.com/orgs/vpo-tusur/discussions/17):
```json
{
	"title": "<название задачи>",
	"description": "<описание задачи>",
	"due_date": "<дата задачи в формате UNIX timeshtamp>"
}
```
2. Сервер обрабатывает запрос и сохраняет новую задачу.
3. Сервер возвращает ответ 201 Created.
Формат тела ответа:
```json
{
        "id": "<task_id>",
	"title": "<название задачи>",
	"description": "<описание задачи>",
	"due_date": "<дата задачи в формате UNIX timeshtamp>"
}
```

## Альтернативная последовательность - в теле запроса не передано поле `title` 
1. Если при обработке запроса в теле запроса не будет обнаружено поле `title` сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `body, title`.

## Альтернативная последовательность - в теле запроса поле `title` содержит пустую строку 
1. Если при обработке запроса в теле запроса поле `title` будет содержать пустую строку сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `body, title`, длина строки быть не менее 1 символа.

## Альтернативная последовательность - в теле запроса поле `title` содержит значение некорректного типа
1. Если при обработке запроса в теле запроса поле `title` будет содержать значение некорректного типа сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `body, title`, ошибка проверки типов.

## Альтернативная последовательность - в теле запроса не передано поле `description`
1. Если при обработке запроса в теле запроса не будет обнаружено поле `description`, поле инициализируется `NULL`.
2. Продолжение основного сценария п.2

## Альтернативная последовательность - в теле запроса поле `description` содержит пустую строку
1. Если при обработке запроса в теле запроса поле `description` содержит пустую строку, поле `description` инициализируется пустой строкой.
2. Продолжение основного сценария п.2

## Альтернативная последовательность - в теле запроса поле `description` содержит значение некорректного типа
1. Если при обработке запроса в теле запроса поле `description` будет содержать значение некорректного типа сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `body, description`, ошибка проверки типов.

## Альтернативная последовательность - в теле запроса не передано поле `due_date`
1. Если при обработке запроса в теле запроса не будет обнаружено поле `due_date`, поле `due_date` инициализируется текущей датой.
2. Продолжение основного сценария п.2

## Альтернативная последовательность - в теле запроса передано некорректное значение `due_date`
1. Если при обработке запроса в теле запроса поле `due_date` будет содержать данные в некорректном формате, сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `body, due_date`, ошибка проверки типов.

## Альтернативная последовательность - в теле запроса значение `due_date` соответствует прошедшей дате
1. Если при обработке запроса в теле запроса поле `due_date` будет указывать на дату прошедшего периода, сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `body, due_date`, ограничение целостности - дата должна соответствовать текущей или грядущей дате.

## Исключительные последовательности
1. Если при обработке запроса возникает ошибка на стороне сервера, сервер возвращает ответ 500 Internal Server Error.
Формат ответа в соответствии с [ТЗ](https://github.com/orgs/vpo-tusur/discussions/17):
```json
"msg": "Произошла ошибка на стороне сервера. Пожалуйста, попробуйте еще раз позже."
```

**Comment by FaerEagle** [comment]
Закрепляю за собой эту задачу

**Comment by FaerEagle** [comment]
1. Стоит описать альтернативные последовательности в случаях, если пользователь не заполнил какое-либо значение в одном из полей задачи (title, description, due_date).
2. Стоит подробнее описать назначение поля due_date в структуре отправляемых данных. Из описания фичи не ясно, должен ли пользователь сам заполнять это поле или оно автоматически заполняется текущей датой, так как в пункте 2 основного сценария использования написано «добавляет новую задачу в список задач на день (какой день, указанный пользователем или же текущий, а может еще какой)». Возможно, стоит написать просто список задач, так как исходя из ТЗ, все задачи хранятся в одном списке, а не списке по конкретному дню.

**Comment by asmazovec** [comment]
@FaerEagle, 
>  Возможно, стоит написать просто список задач, так как исходя из ТЗ, все задачи хранятся в одном списке, а не списке по конкретному дню.

Возможно, добавим это как фичу "массовое создание задач за дату", пока необходимость есть добавлять только по одной задаче за раз.

**Comment by FaerEagle** [comment]
@asmazovec 
1. Все еще остается открытым вопрос по формулировке второго пункта основного сценария использования. В прошлом комментарии был вопрос именно к словам "добавляет новую задачу в список задач на день", но списка задач на день по ТЗ как такового нет, есть просто список всех задач. Лучше будет написать "добавляет новую задачу в список задач". В этом был основной посыл комментария.
2. Цель фичи сформулирована следующим образом "Позволяет пользователю добавлять новые задачи в список задач на выбранную дату". В таком случае возникает вопрос о достижимости альтернативной последовательности - в теле запроса передано некорректное значение due_date, если пользователь будет выбирать дату (например из календаря), а не вписывать ее в поле самостоятельно. Но в целом сценарий можно оставить с точки зрения проверки серверной части без какого-либо пользовательского интерфейса. Это так, вопрос больше на уточнение.

**Comment by asmazovec** [comment]
@FaerEagle, задумка такая, что проект представляет собой исключительно rest api сервис, для которого уже каждый может написать свой фронт, типа как работают метео сервисы - ты покупаешь токен на 100 запросов в месяц и ходишь по нему чисто за данными, а интерфейсы делаются уже кем угодно - хочешь, делаешь свою приложуху с прогнозом погоды, хочешь, к умному дому подключаешь тригеры на закрывание сарая.

По первому пункту под "списком задач" подразумевается то, что если мы заводим задачу, то она привязана к какой-либо дате и если накидывать задачи на одну дату, то сформируется список этих задач, а так, чисто с технической точки зрения это действительно будет один единственный непрерывный список записей в бд

**Comment by asmazovec** [comment]
Принимаю твое мнение, чище звучит

**Comment by FaerEagle** [comment]
1. Основной сценарий: проверки успешно пройдены;
2. Альтернативная последовательность - в теле запроса не передано поле title: проверки успешно пройдены;
3. Альтернативная последовательность - в теле запроса поле title содержит значение некорректного типа: вопрос о достижимости данного сценария, так как что бы ни отправлялось в запросе, оно приводится к типу string;
4. Альтернативная последовательность - в теле запроса не передано поле description: проверки успешно пройдены;
5. Альтернативная последовательность - в теле запроса поле description содержит пустую строку: проверки успешно пройдены;
6. Альтернативная последовательность - в теле запроса поле description содержит значение некорректного типа: аналогично п. 3;
7. Альтернативная последовательность - в теле запроса не передано поле due_date: проверки успешно пройдены;
8. Альтернативная последовательность - в теле запроса передано некорректное значение due_date: проверки успешно пройдены;
9. Альтернативная последовательность - в теле запроса значение due_date соответствует прошедшей дате: проверки успешно пройдены.

**Comment by asmazovec** [comment]
@FaerEagle Если передавать title: 123 ?

**Comment by FaerEagle** [comment]
Если передавать прямо вот так, без кавычек, то это уже не будет json форматом и придет соответствующая ошибка, можно ли это считать как случай данного сценария?

**Comment by FaerEagle** [comment]
Хотя нет, я понял свою ошибку, ты все верно написал

**Comment by FaerEagle** [comment]
> [@asmazovec](https://github.com/asmazovec)
> 
> 1. Основной сценарий: проверки успешно пройдены;
> 2. Альтернативная последовательность - в теле запроса не передано поле title: проверки успешно пройдены;
> 3. Альтернативная последовательность - в теле запроса поле title содержит значение некорректного типа: вопрос о достижимости данного сценария, так как что бы ни отправлялось в запросе, оно приводится к типу string;
> 4. Альтернативная последовательность - в теле запроса не передано поле description: проверки успешно пройдены;
> 5. Альтернативная последовательность - в теле запроса поле description содержит пустую строку: проверки успешно пройдены;
> 6. Альтернативная последовательность - в теле запроса поле description содержит значение некорректного типа: аналогично п. 3;
> 7. Альтернативная последовательность - в теле запроса не передано поле due_date: проверки успешно пройдены;
> 8. Альтернативная последовательность - в теле запроса передано некорректное значение due_date: проверки успешно пройдены;
> 9. Альтернативная последовательность - в теле запроса значение due_date соответствует прошедшей дате: проверки успешно пройдены.

Обновление по пунктам 3 и 6: проверки успешно пройдены.
