### ISSUE TITLE
Актуализация существующей задачи

### ISSUE THREAD

**Issue by asmazovec** [vpo-tusur/todo-api#19]
## Цель фичи

Позволяет пользователю обновлять информацию о существующей задаче. Задача изменяется полностью за раз.

## Основной сценарий использования
1. Пользователь отправляет PUT запрос на URL `/tasks/{task_id}` с телом запроса, содержащим обновленную информацию о задаче.
Формат запроса в соответствии с [ТЗ](https://github.com/orgs/vpo-tusur/discussions/17):
```json
{
	"title": "<обновленное название задачи>",
	"description": "<обновленное описание задачи>",
	"due_date": "<обновленная дата задачи>"
}
```
2. Сервер обрабатывает запрос и обновляет информацию о задаче.
3. Сервер возвращает ответ 200 OK.
Формат тела ответа:
```json
{
        "id": "<task_id>",
	"title": "<обновленное название задачи>",
	"description": "<обновленное описание задачи>",
	"due_date": "<обновленная дата задачи>"
}
```

## Альтернативная последовательность - задача по `task_id` не существует
1. Сервер возвращает ответ 404 Not Found.
Формат ответа: 
```json
"msg": "Задача по идентификатору '<task_id>' не найдена"
```

## Альтернативная последовательность - в теле запроса не передано поле `title` 
1. Если при обработке запроса в теле запроса не будет обнаружено поле `title` сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `body, title`.

## Альтернативная последовательность - в теле запроса поле `title` содержит пустую строку 
1. Если при обработке запроса в теле запроса поле `title` будет содержать пустую строку сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `body, title`, длина строки быть не менее 1 символа.

## Альтернативная последовательность - в теле запроса не передано поле `description`
1. Если при обработке запроса в теле запроса не будет обнаружено поле `description` или поле `description` содержит пустую строку, поле `description` инициализируется пустой строкой.
2. Продолжение основного сценария п.2

## Альтернативная последовательность - в теле запроса поле `description` содержит значение некорректного типа
1. Если при обработке запроса в теле запроса поле `description` будет содержать значение некорректного типа сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `body, description`, ошибка проверки типов.

## Альтернативная последовательность - в теле запроса поле `title` содержит значение некорректного типа
1. Если при обработке запроса в теле запроса поле `title` будет содержать значение некорректного типа сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `body, title`, ошибка проверки типов.

## Альтернативная последовательность - в теле запроса не передано поле `due_date`
1. Если при обработке запроса в теле запроса не будет обнаружено поле `due_date`, поле `due_date` инициализируется текущей датой.
3. Продолжение основного сценария п.2

## Альтернативная последовательность - в теле запроса передано некорректное значение `due_date`
1. Если при обработке запроса в теле запроса поле `due_date` будет содержать данные в некорректном формате, сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `body, due_date`, ошибка проверки типов.

## Альтернативная последовательность - в теле запроса значение `due_date` соответствует прошедшей дате
1. Если при обработке запроса в теле запроса поле `due_date` будет указывать на дату прошедшего периода, сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `body, due_date`, ограничение целостности - дата должна соответствовать текущей или грядущей дате.

## Исключительные последовательности
1. Если при обработке запроса возникает ошибка на стороне сервера, сервер возвращает ответ 500 Internal Server Error.
Формат ответа в соответствии с [ТЗ](https://github.com/orgs/vpo-tusur/discussions/17):
```json
"msg": "Произошла ошибка на стороне сервера. Пожалуйста, попробуйте еще раз позже."
```

**Comment by xXNegativeXx** [comment]
Беру

**Comment by xXNegativeXx** [comment]
1) Нужно описать обработку случая, когда поля "title" или "description" не заполнены.
2) Стоит добавить пояснения к тому, как будет обрабатываться поле "due_date" в случаях, когда в нём некорректные данные или оно просто не заполнено.

**Comment by asmazovec** [comment]
Просто для справки дам пояснения - метод PUT полностью меняет все поля за раз. Альтернативный метод PATCH предназначен для того, чтобы поправлять значения в некоторых полях, при этом остальные поля сохранят свои значения. В данной задаче используется метод PUT.

1, 2 - Дополнил сценарии аналогично с #18

**Comment by asmazovec** [comment]
Разработка назначена на @mottyas

**Comment by xXNegativeXx** [comment]
1. Не работает альтернативный сценарий "в теле запроса не передано поле description".
Ожидаемый результат: Поле "description" становится пустой строкой.
Фактический результат: Появляется ошибка "string_too_short":
![Image](https://github.com/vpo-tusur/todo-api/assets/160238937/4aa0c8fe-279e-4862-aace-509b39f58b92)

2. Не работает альтернативный сценарий "в теле запроса не передано поле due_date".
Ожидаемый результат: параметр "due_date" принимает значение текущей даты.
Фактический результат: Появляется ошибка "date_from_datetime_parsing":
![Image](https://github.com/vpo-tusur/todo-api/assets/160238937/cad7552e-a4d0-4518-8e1d-79ac3489ff52)

**Comment by mottyas** [comment]
> 1. Не работает альтернативный сценарий "в теле запроса не передано поле description".
>        Ожидаемый результат: Поле "description" становится пустой строкой.
>        Фактический результат: Появляется ошибка "string_too_short":
>        ![Image](https://private-user-images.githubusercontent.com/160238937/322707658-4aa0c8fe-279e-4862-aace-509b39f58b92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDg0NTcsIm5iZiI6MTcxMzI0ODE1NywicGF0aCI6Ii8xNjAyMzg5MzcvMzIyNzA3NjU4LTRhYTBjOGZlLTI3OWUtNDg2Mi1hYWNlLTUwOWIzOWY1OGI5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwNjE1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmJkMDU0ZWY4ZmRlZDdhYzE2MmNmNGM3Yzg0NWZiYjFhZDUwM2UzMGQ3OGI0ZDUwODM3NTk0MDE0MjYwMDJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yzs2Buw7kZ8oraZXkLkuR2hCszmeNCMbEazYl5MsItg)
> 
>     2. Не работает альтернативный сценарий "в теле запроса не передано поле due_date".
>        Ожидаемый результат: параметр "due_date" принимает значение текущей даты.
>        Фактический результат: Появляется ошибка "date_from_datetime_parsing":
>        ![Image](https://private-user-images.githubusercontent.com/160238937/322708372-cad7552e-a4d0-4518-8e1d-79ac3489ff52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDg0NTcsIm5iZiI6MTcxMzI0ODE1NywicGF0aCI6Ii8xNjAyMzg5MzcvMzIyNzA4MzcyLWNhZDc1NTJlLWE0ZDAtNDUxOC04ZTFkLTc5YWMzNDg5ZmY1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwNjE1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2YwOGExYzZmM2Q5NjljYjFkZjRmYTY4OTEzNGEyMWIxOTdhY2ZlMGY0MGQwMTA2ZGNiMjAyYmU4Yjg0N2JlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R1zfx_p25f_Pvt7JrgKtqHIfIJAEi6QDYaUtdK4rE6Q)

По поводу второго пункта: вы в запросе передаете невалидные данные, в ТЗ указано, что возвращается текущая дата в случае если поле due_date вообще не указано. В случае, описанном в репорте, на вход подаются невалидные данные (пустая строка), собственно, поэтому возвращается исключение о некорректных данных.

**Comment by asmazovec** [comment]
п.2 - Соглашусь с @mottyas, в запросе в поле due_date передана пустая строка, - некорректный формат даты

**Comment by asmazovec** [comment]
@xXNegativeXx исправления готовы к тестированию
