### ISSUE TITLE
Удаление существующей задачи

### ISSUE THREAD

**Issue by asmazovec** [vpo-tusur/todo-api#20]
## Цель фичи

Позволяет пользователю удалять задачи.

## Основной сценарий использования
1. Пользователь отправляет DELETE запрос на URL `/tasks/{task_id}`. Тело запроса не требуется.
3. Сервер обрабатывает запрос и удаляет задачу по переданному `task_id`.
4. Сервер возвращает ответ 200 OK.

## Альтернативная последовательность - задача по `task_id` не найдена
1. Если задача с указанным `task_id` не найдена, сервер возвращает ответ 404 Not Found.
Формат ответа: 
```json
"msg": "Задача по идентификатору '<task_id>' не найдена"
```

## Альтернативная последовательность - `task_id` передан в некорректном формате
1. Если при обработке запроса в теле запроса поле `task_id` будет содержать значение некорректного типа сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `query, task_id`, ошибка проверки типов.

## Исключительные последовательности
1. Если при обработке запроса возникает ошибка на стороне сервера, сервер возвращает ответ 500 Internal Server Error.
Формат ответа в соответствии с [ТЗ](https://github.com/orgs/vpo-tusur/discussions/17):
```json
"msg": "Произошла ошибка на стороне сервера. Пожалуйста, попробуйте еще раз позже."
```

**Comment by FaerEagle** [comment]
В целом все нормально, единственное, как и вопрос в #18 по поводу словосочетания "список задач на день" в цели фичи и п.2 основного сценария использования. Рекомендуется также проверить все остальные фичи на наличие подобного описания и исправить, чтобы больше не возвращаться к этому.

**Comment by asmazovec** [comment]
Разработка назначена на @OgibalovaEV

**Comment by asmazovec** [comment]
@FaerEagle 
П1, думаю можем включить это во второй релиз, добавление новых полей в ответе сервера не будет противоречить нашей конвенции об обратной совместимости API (надо это где-нибудь зафиксировать)

П3, в задаче получения списка задач на день указано, что запрос без параметров должен интерпретироваться как список задач на текущую дату
