### ISSUE TITLE
Получение списка задач на день

### ISSUE THREAD

**Issue by asmazovec** [vpo-tusur/todo-api#21]
## Цель фичи

Позволяет пользователю получать список задач за выбранную дату.

## Основной сценарий использования

1. Пользователь отправляет GET запрос на URL `/tasks?date={дата в формате RFC 3339}`.
2. Сервер обрабатывает запрос и возвращает список задач на указанную дату.
3. Сервер возвращает ответ 200 OK с телом ответа, содержащим список задач.
Формат ответа в соответствии с [ТЗ](https://github.com/orgs/vpo-tusur/discussions/17):
 ```json
[
    {
      "id": 1,
      "title": "Задача 1",
      "description": "Описание задачи 1",
      "due_date": "2023-04-15"
    },
    {
      "id": 2,
      "title": "Задача 2",
      "description": "Описание задачи 2",
      "due_date": "2023-04-15"
    },
    ...
]
```

## Альтернативная последовательность - в запросе не передан параметр `date`

1. Если при обработке запроса в параметрах url запроса не будет обнаружено поле `date`, в качестве значения параметра `date` используется текущая дата на сервере.
2. Продолжение основного сценария п.2.

## Альтернативная последовательность - в параметре запроса `date` передано некорректное значение
1. Если при обработке запроса в url запроса параметр `date` будет содержать данные в некорректном формате, сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `query, date`.

## Исключительные последовательности

1. Если при обработке запроса возникает ошибка на стороне сервера, сервер возвращает ответ 500 Internal Server Error.
```json
"msg": "Произошла ошибка на стороне сервера. Пожалуйста, попробуйте еще раз позже."
```

**Comment by chzhen-g** [comment]
1 В альтернативной последовательности в сообщении об ошибке 
{
	"message": "Неверный формат даты в параметре '<имя параметра>'"
}
думаю следует поменять "<имя параметра>" на "date"
2 В основном сценарии использования в примере ответа приходит список задач с разными датами (за 15 и 16 апреля), когда в фиче указано - получение списка задач за день
{
 "tasks": [
   {
     "id": 1,
     "title": "Задача 1",
     "description": "Описание задачи 1",
     "due_date": "2023-04-15"
   },
   {
     "id": 2,
     "title": "Задача 2",
     "description": "Описание задачи 2",
     "due_date": "2023-04-16"
   },
   ...
 ]
}
В ТЗ так же стоит исправить этот момент 
3 Стоит добавить альтернативную последовательность, в случаи когда пользователь не указал параметр "date" (хоть это и указано в целях фичи).
4 В 4 шаге основного сценария опечатка лишняя часть - "## Альтернативные последовательности"

**Comment by asmazovec** [comment]
Не брать в разработку, пока не готова #23

**Comment by chzhen-g** [comment]
1.  Основной сценарий: проверки успешно пройдены;
2.  Альтернативная последовательность - в запросе не передан параметр date: проверки успешно пройдены;
3.  Альтернативная последовательность - в параметре запроса date передано некорректное значение: проверки успешно пройдены.
