### ISSUE TITLE
Получение списка задач на неделю

### ISSUE THREAD

**Issue by asmazovec** [vpo-tusur/todo-api#22]
## Цель фичи

Позволяет пользователю получать список созданных задач на неделю.

## Основной сценарий использования

1. Пользователь отправляет GET запрос на URL `/tasks?date={дата в формате RFC 3339}&week=true`.
2. Сервер обрабатывает запрос и возвращает список задач на указанную неделю.
4. Сервер возвращает ответ 200 OK с телом ответа, содержащим список задач.
Формат ответа в соответствии с [ТЗ](https://github.com/orgs/vpo-tusur/discussions/17):
```json
[
    {
      "id": 1,
      "title": "Задача 1",
      "description": "Описание задачи 1",
      "due_date": "2023-04-15"
    },
    {
      "id": 2,
      "title": "Задача 2",
      "description": "Описание задачи 2",
      "due_date": "2023-04-16"
    },
    ...
]
```

## Альтернативная последовательность - в запросе не передан параметр `date`
1. Если при обработке запроса в параметрах url запроса не будет обнаружено поле `date`,  в качестве значения параметра `date` используется текущая дата на сервере.
2. Продолжение основного сценария п.2.

## Альтернативная последовательность - в параметре запроса `date` передано некорректное значение
1. Если при обработке запроса в url запроса параметр `date` будет содержать данные в некорректном формате, сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `query, date`.

## Альтернативная последовательность - в параметре запроса `week` передано некорректное значение
1. Если при обработке запроса в url запроса параметр `week` будет содержать данные в некорректном формате, сервер возвращает ответ 422 Bad Request.
Формат ответа: ошибка валидации Pydantic для поля `query, week`.

## Альтернативная последовательность - в параметре запроса `week` не передано значение
1. Исполняется основной сценарий из задачи #21.

## Альтернативная последовательность - в параметре запроса `week` передано значение `false`
1. Исполняется основной сценарий из задачи #21.

## Исключительные последовательности

1. Если при обработке запроса возникает ошибка на стороне сервера, сервер возвращает ответ 500 Internal Server Error.
Формат ответа в соответствии с [ТЗ](https://github.com/orgs/vpo-tusur/discussions/17):
```
"msg": "Произошла ошибка на стороне сервера. Пожалуйста, попробуйте еще раз позже."
```

**Comment by chzhen-g** [comment]
1. В альтернативной последовательности в сообщении об ошибке
```
{
"message": "Неверный формат даты в параметре '<имя параметра>'"
}
``` 
думаю следует поменять "<имя параметра>" на "date"

2. Стоит добавить альтернативную последовательность, в случаях когда пользователь не указал параметр "date".

**Comment by asmazovec** [comment]
Не брать, пока не готова #23

**Comment by chzhen-g** [comment]
@Sogato @asmazovec 
1. Основной сценарий:
      Уточнение: под неделей предполагается 7 дней или календарная неделя? На данный момент выводится список задач на 7 дней.
2. Альтернативная последовательность - в запросе не передан параметр date: 
       Ожидаемый результат: Должен прийти список задач на текущую неделю 
       Фактический результат: Приходит список задач только за текущую дату на сервере 
![image](https://github.com/vpo-tusur/todo-api/assets/81752682/feac5564-6641-47b2-b39f-fb373a3f2d7a)

3. Альтернативная последовательность - в параметре запроса date передано некорректное значение : Проверки успешно пройдены;
4. Альтернативная последовательность - в параметре запроса week передано некорректное значение: Проверки успешно пройдены;
5. Альтернативная последовательность - в параметре запроса week не передано значение: Проверки успешно пройдены;
6. Альтернативная последовательность - в параметре запроса week передано значение false: Проверки успешно пройдены.

**Comment by asmazovec** [comment]
@chzhen-g 7 дней от выбранной даты

**Comment by chzhen-g** [comment]
1. Основной сценарий: Проверки успешно пройдены;
2. Альтернативная последовательность - в запросе не передан параметр date: Проверки успешно пройдены;
3. Альтернативная последовательность - в параметре запроса date передано некорректное значение : Проверки успешно пройдены;
4. Альтернативная последовательность - в параметре запроса week передано некорректное значение: Проверки успешно пройдены;
5. Альтернативная последовательность - в параметре запроса week не передано значение: Проверки успешно пройдены;
6. Альтернативная последовательность - в параметре запроса week передано значение false: Проверки успешно пройдены.
