### ISSUE TITLE
Получение списка задач за период

### ISSUE THREAD

**Issue by asmazovec** [vpo-tusur/todo-api#23]
## Цель фичи

Позволяет пользователю получать список задач за выбранный период.

## Основной сценарий использования

1. Пользователь отправляет GET запрос на URL `/tasks?start_date={дата в формате RFC 3339}&end_date={дата в формате RFC 3339}`.
2. Сервер обрабатывает запрос и возвращает список задач за указанный период.
3. Сервер возвращает ответ 200 OK с телом ответа, содержащим список задач.
Формат ответа в соответствии с [ТЗ](https://github.com/orgs/vpo-tusur/discussions/17):
```json
[
    {
      "id": 1,
      "title": "Задача 1",
      "description": "Описание задачи 1",
      "due_date": "2023-04-15"
    },
    {
      "id": 2,
      "title": "Задача 2",
      "description": "Описание задачи 2",
      "due_date": "2023-04-16"
    },
    ...
]
```
_В случае, если за указанный период не будет найдено ни одной задачи, формат ответа должен следовать правилам формирования [пустого списка json](https://docs.botmother.ru/article/54122#empty_list):
```json
[ ]
```

## Альтернативные последовательности
1. Если пользователь отправляет запрос с некорректными датами, сервер возвращает ответ 422 Bad Request с сообщением об ошибке.
Формат ответа: ошибка валидации Pydantic для поля `query, <поле>`.

## Исключительные последовательности
1. Если при обработке запроса возникает ошибка на стороне сервера, сервер возвращает ответ 500 Internal Server Error.
Формат ответа в соответствии с [ТЗ](https://github.com/orgs/vpo-tusur/discussions/17):
```json
"msg": "Произошла ошибка на стороне сервера. Пожалуйста, попробуйте еще раз позже."
```

**Comment by xXNegativeXx** [comment]
Забираю эту задачу

**Comment by xXNegativeXx** [comment]
1) Не понятно, как будет вести себя сервер в случае, если за указанный пользователем период не будет ни одной задачи.
2) Есть предложение добавить вывод количества задач за указанный период.

**Comment by asmazovec** [comment]
@xXNegativeXx, спасибо за ответ
п.1 - добавил описание ответа в случае отсутствия задач за выбранный период, 
п.2 - таких требований заявлено в ТЗ небыло

**Comment by asmazovec** [comment]
Разработка назначена на @Sogato

**Comment by xXNegativeXx** [comment]
При вводе точек вместо дефисов в поля "start_date" или "end_date" не появляется ошибка.
Ожидаемый результат: Сервер возвращает ответ 422 Bad Request с сообщением об ошибке.

**Comment by xXNegativeXx** [comment]
1) Ошибка в альтернативном сценарии "В запросе передан параметр week со значением True".
Предусловие: Поле date не заполнено. В параметре week передано True. Поля start_date и end_date заполнены корректно. Параметр start_date меньше end_date.
Ожидаемый результат: Сервер возвращает ответ 400 с сообщением "Запрос не может одновременно содержать 'week' и 'start_date'/'end_date'. Пожалуйста, укажите только один из этих параметров.".
Фактический результат: Сервер возвращает ответ 200 с телом ответа, содержащим список задач за НЕДЕЛЮ, начиная с текущей даты.
![Image](https://github.com/vpo-tusur/todo-api/assets/160238937/9aa0a5fe-71a5-4865-bf4c-66fe9ade0184)

2) Ошибка в альтернативном сценарии "В запросе не передано поле start_date.".
Предусловие: Поля date и week не заполнены. Поле start_date не заполнено. Поле end_date заполнено корректно.
Ожидаемый результат: Сервер возвращает ответ 422.
Фактический результат: Сервер возвращает ответ 200 с телом ответа, содержащим список задач на текущую дату.
![Image](https://github.com/vpo-tusur/todo-api/assets/160238937/a640809d-d832-4932-a7ea-7d3776af13d4)

3) Ошибка в альтернативном сценарии "В запросе не передано поле end_date.".
Предусловие: Поля date и week не заполнены. Поле end_date не заполнено. Поле start_date заполнено корректно.
Ожидаемый результат: Сервер возвращает ответ 422.
Фактический результат: Сервер возвращает ответ 200 с телом ответа, содержащим список задач на текущую дату.
![Image](https://github.com/vpo-tusur/todo-api/assets/160238937/0097745e-d68c-4ee4-b525-fe083f735f8e)
