### ISSUE TITLE
Описать работу с инструментами командной разработки GH

### ISSUE THREAD

**Issue by asmazovec** [vpo-tusur/todo-api#3]
Необходимо описать основной флоу работы с GitHub:

Как заводить Issue
Как задавать в них сроки выполнения и оценку сложности
Как переводить задачи по статусам выполнения
Как работать с pull-реквестами в веб-интерфейсе
Как ориентироваться в проектах

**Comment by asmazovec** [comment]
@mottyas  Отредактируй пожалуйста задачу - добавь что конкретно планируешь описать и переведи в статус In Progress

**Comment by asmazovec** [comment]
Либо Ready если не готов сейчас заняться ей

**Comment by mottyas** [comment]
Накидал немного инфы, можно будет в будущем добавить на вики (Неокончательный вариант, еще буду править).

[Описание работы с инструментами коммандной разработки GitHub.md](https://github.com/vpo-tusur/todo-api/files/14651537/GitHub.md)
