### ISSUE TITLE
Провести регресс по релизу

### ISSUE THREAD

**Issue by asmazovec** [vpo-tusur/todo-api#52]
# План регрессионного тестирования
- [x] Подготовить план тестирования
- [x] Провести регрессионное тестирование предрелизной версии
- [x] Завести задачи по найденным багам

# Задачи релиза

1. #18 
2. #19 
3. #20 
4. #21 
5. #22 
6. #23

**Comment by xXNegativeXx** [comment]
Результаты проверок:
https://docs.google.com/spreadsheets/d/1g6otvZAPtoTA2s0Tf6TLuxiN21SQqI7W-ZtvTXeCut0/edit#gid=0
